### ISSUE TITLE
Exception after calling require("frida-fs")

### ISSUE THREAD

**Issue by shad0whunt3r0** [nowsecure/frida-fs#11]
I got exception message from frida server after calling require("frida-fs")

This is my js:

console.log("[*] FRIDA started");
var unlinkPtr = Module.findExportByName(null, 'unlink');
'use strict';
var fs = require('frida-fs');

Error message: 
message:', {u'columnNumber': 1, u'description': u"ReferenceError: identifier 'require' undefined", u'fileName': u'/script1.js', u'lineNumber': 8, u'type': u'error', u'stack': u"ReferenceError: identifier 'require' undefined\n    at [anon] (duk_js_var.c:1208)\n    at /script1.js:8"}, 'data:', None)

**Comment by trufae** [comment]
You have to use frida-compile

**Comment by shad0whunt3r0** [comment]
> You have to use frida-compile
> […](#)
> On 5 Jun 2019, at 04:38, shad0whunt3r0 ***@***.***> wrote: I got exception message from frida server after calling require("frida-fs") This is my js: console.log("[*] FRIDA started"); var unlinkPtr = Module.findExportByName(null, 'unlink'); 'use strict'; var fs = require('fs'); Error message: message:', {u'columnNumber': 1, u'description': u"ReferenceError: identifier 'require' undefined", u'fileName': u'/script1.js', u'lineNumber': 8, u'type': u'error', u'stack': u"ReferenceError: identifier 'require' undefined\n at [anon] (duk_js_var.c:1208)\n at /script1.js:8"}, 'data:', None) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

hmm, why should i use frida-compile?
I'm injecting the js into an android application, everything works, I can't just use require('frida-fs');

**Comment by trufae** [comment]
Because frida cant handle require and you need to provide a single script with no dependencies in the agent side in order to make it work. So you have to babelifyit or so, frida-compile simplifies the process. You can look at how its done in r2frida
