### ISSUE TITLE
How to make a new file and write some string to it

### ISSUE THREAD

**Issue by wickywaka** [nowsecure/frida-fs#7]
I am able to write to files that already exists. It opens the file and seek to 0 position. It doesn't remove contents that are already in the file but subsequent writes will overwrite the characters on that position.

What I couldn't figure out is how to make a new file and write something to it?

Here is the error message that I get:

```
{u'columnNumber': 1, u'description': u"ReferenceError: identifier 'strerror' undefined", u'fileName': u'script1.js', u'lineNumber': 2396, u'type': u'error', u'stack': u"ReferenceError: identifier 'strerror' undefined\n    at [anon] (duk_js_var.c:1207)\n    at getErrorString (node_modules/frida-fs/index.js:491)\n    at WriteStream (node_modules/frida-fs/index.js:149)\n    at createWriteStream (node_modules/frida-fs/index.js:572)\n    at index.js:10\n    at frida/node_modules/frida-java/lib/vm.js:39\n    at y (frida/node_modules/frida-java/index.js:325)\n    at frida/node_modules/frida-java/index.js:308\n    at input:1"}

```

**Comment by waqarrashid33** [comment]
Update:
From the description it was later clear that it was the issue of Read only file system. So far I could only manage to make files in location where the application has write access. In android that directory is located in /data/data/package.name/files. Below is the agent code witch which you can make a file in  that directory and then read it.

``` Javascript
'use strict';

const fs = require("frida-fs");

Java.perform(function () {

    var file = new File("/data/data/org.wikipedia/files/file_new.txt","w");
    file.write("Hi Hola Hello");
    file.close();

    send("sending file contents");
    send(JSON.stringify(fs.readFileSync("/data/data/org.wikipedia/files/file_new.txt")));

});
```

I will leave this issue open as originally I wanted to write to /data/local/tmp which is still read-only. Any help in that matter will be highly appreciated.

Waqar

**Comment by srcdes** [comment]
Why `ReferenceError: identifier 'require' undefined` happens?

**Comment by srcdes** [comment]
@waqarrashid33 What about to write file in `/data/local/tmp`? This directory permits access from device without rooting. Can we write a file in this directory? I've tried this. But `adb shell`'s `ls -al` doesn't show the created file. Absolutely, i can open the file which was created before. Very weired.

**Comment by srcdes** [comment]
How this integrate with java byte array gotten from hooked method's return value?

**Comment by srcdes** [comment]
You can also use Java `FileOutputStream` instead.

**Comment by oleavr** [comment]
This is now also supported through `writeFile()` and `writeFileSync()`.

**Comment by brownmouse10** [comment]
> Update: Seems that we have write permissions only to application space and by using the script below, one can read from application files directory which is `/data/data/com.package.name/`,
> 
> ```js
> 'use strict';
> 
> const fs = require("frida-fs");
> 
> Java.perform(function () {
>     // a,w,r,w+,r+ modes, same as fopen in c
>     var file = new File("/data/data/org.wikipedia/files/file_new.txt","w");
>     file.write("Hi Hola Hello Hallo");
>     file.close();
> 
>     send("sending file contents");
>     send(fs.readFileSync("/data/data/org.wikipedia/files/file_new.txt"));
> 
> });
> ```

would you know what this path is on iOS?
